### ISSUE TITLE
Bug report: бинды не работают/keybinds not working

### ISSUE THREAD

**Issue by BLACKUM** [AniLabX/AniLabXMAX#1]
Как воспроизвести/How to reproduce:
//ru
1.Открыть настройки
2.Раздел мангаридер, подраздел кнопки управления
3.Попытка изменить бинд приводит к ошибке
//eng
1.Open settings
2.Section Manga reader, subsection Control Buttons
3.Trying to change the bind results in an error
версия/version:[v1.0b1](https://github.com/AniLabX/AniLabXMAX/releases/tag/v1.0b1)
logs:[exception-2024-05-08T16.04.56.952+03.txt](https://github.com/AniLabX/AniLabXMAX/files/15249382/exception-2024-05-08T16.04.56.952%2B03.txt)
![S7yxuxhn0k](https://github.com/AniLabX/AniLabXMAX/assets/58638340/e69a3d5e-08dc-42c1-b138-48eeb75d85c6)

**Comment by CrazyXacker** [comment]
Исправлено
