### ISSUE TITLE
Bug report: Некорректно закрывается окно web-плеера

### ISSUE THREAD

**Issue by AlexYukikaze** [AniLabX/AniLabXMAX#2]
При закрытии веб-плеера окно закрывается но звук продолжает работать пока не закроешь приложение. Если отрыть веб-плеер еще раз и так же закрыть то звук начинает накладываться множество раз. 
Проверял на Anidub.vip источник SIBNET, на Fullmetal Alchemist: Brotherhood

**Comment by CrazyXacker** [comment]
Исправлено
