### ISSUE TITLE
Bug report: Нажатие любой кнопки в разделе настроек хранилище вызывает ошибку/Clicking any button in the storage settings section causes an error

### ISSUE THREAD

**Issue by BLACKUM** [AniLabX/AniLabXMAX#5]
//ru
Описание:
При нажатии любой кнопки в настройки>хранилище происходит ошибка
Как воспроизвести:
1.Открыть настройки
2.Выбрать раздел хранилище
3.При нажатии любой кнопки
![AniLabXMAX_v1 0b1_win64_ANYppgPdJx](https://github.com/AniLabX/AniLabXMAX/assets/58638340/e2db04e7-fae1-4414-95bd-d832d25f9d1a)
происходит ошибка.

//eng
Description:
When you click any button in settings>storage, an error occurs
How to reproduce:
1.Open settings
2.Select storage section
3.When pressing any button
![AniLabXMAX_v1 0b1_win64_ANYppgPdJx](https://github.com/AniLabX/AniLabXMAX/assets/58638340/e2db04e7-fae1-4414-95bd-d832d25f9d1a)
error occurs.

logs:
[exception-2024-05-08T19.09.05.270+03.txt](https://github.com/AniLabX/AniLabXMAX/files/15251701/exception-2024-05-08T19.09.05.270%2B03.txt)
[exception-2024-05-08T18.16.58.972+03.txt](https://github.com/AniLabX/AniLabXMAX/files/15251692/exception-2024-05-08T18.16.58.972%2B03.txt)

Версия/Version:[v1.0b1](https://github.com/AniLabX/AniLabXMAX/releases/tag/v1.0b1)

**Comment by CrazyXacker** [comment]
Исправлено
